Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,7 +11,8 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
       - name: Configure CMake
         run: cmake -S . -B build
@@ -19,14 +20,15 @@ jobs:
       - name: Build
         run: cmake --build build --config Debug
 
-      - name: Token Validatin
-        run:
-            if [ -z "${{ secrets.REPO_ENGINE_PAT }}" ]; then
-              echo "token missing"
-              exit 1
-            fi
-            
+      - name: Validate token
+        run: |
+          if [ -z "${{ secrets.REPO_ENGINE_PAT }}" ]; then
+            echo "token missing"
+            exit 1
+          fi
+
       - name: Dispatch to engine
+        if: success()
         uses: peter-evans/repository-dispatch@v4
         with:
           token: ${{ secrets.REPO_ENGINE_PAT }}
